python3: can't open file '/home/ubuntu/FLASK-3FA/mfa.py': [Errno 2] No such file or directory
python3: can't open file '/home/ubuntu/FLASK-3FA/mfa.py': [Errno 2] No such file or directory
python3: can't open file '/home/ubuntu/FLASK-3FA/mfa.py': [Errno 2] No such file or directory
 * Serving Flask app 'app'
 * Debug mode: on
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
 * Serving Flask app 'app'
 * Debug mode: on
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
